version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout

  bundle_dependencies:
    working_directory: ~/simulador-investimento-poupanca
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle

  chrome_test:
    docker:
      - image: circleci/ruby:latest-browsers
    steps:
      - run: 
          name: Bundle install
          command: bundle install --path vendor/bundle
      - run: 
          name: Execute all features scenarios (except @wip tags) on Goole Chrome browser
          command: bundle exec cucumber --profile ci_report --profile not_wip
      - store_test_results:
          path: ~/cucumber/junit.xml
      - store_artifacts:
          path: ~/cucumber/junit.xml
      # Save test results for timing analysis
      - store_test_results:
          path: ~/HTTParty/test_results
      - store_artifacts:
          path: ~/HTTParty/test_results

workflows:
  version: 2
  build_and_test:
#    triggers:
#      - schedule:
#          cron: "* 4 * * *"
#          filters:
#            branches:
#              only: master
    jobs:
      - build
      - bundle_dependencies:
          requires: 
            - build
      - chrome_test:
          requires:
            - bundle_dependencies
      # - firefox_test:
      #     requires:
      #       - bundle_dependencies
      #       - code_analyzer